wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1744125107
    t:
      1:
      - 1
      - 5
      - 9
      - 12
      - 30
      - 41
      - 45
      - 53
      - 54
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 12
      - 30
      - 41
      - 45
      - 53
      - 54
      - 55
      - 103
      3:
      - 2
      - 13
      - 23
      4: 3.10.13
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
