wandb:
  wandb_log: True
  name: 'OOD time'
  project: 'SCREPRODUCE'
  group: 'SC: Prostate Cycle Filtered REPRODUCE'

UI:
  launch: False
  ide: True

hardware:
  device: 0

other:
  experiment_name: True
  verbose: True

data: 
  file_path: '/data/Experiments/Benchmark/scdisentangle/Datasets/preprocessed_datasets/prostate_filtered.h5ad'
  default_normalization: False
  use_counts: True
  label_keys: ['time', 'batchID', 'predType']

  highly_variable: False
  min_gene_counts: False
  min_cell_counts: False
  train_size: 1
  val_size: 0
  test_size: 0
  batch_size: 128
  crispr_data: False
  SUBSET: False

OOD: 
  apply: True
  filter_dict:
    predType: 'Epi_Luminal_2Psca'
    time: 'Insert_OOD'

growing_neurons:
  total_neurons: 8
  lr: 0.001
  decoder_name: 'decoder_post_train'

  prior_mappers:
    mappers:
      time_mapper:
        name: 'time'
        embedder_name: 'time_embedder'

        collapse_name: 'T02_Cast_Day7'
        collapse_target: True

models:
  encoder_pretrain: 
    layers: [2040, 256, 16]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False

  decoder:
    layers: [16, 256, 256, 256, 2040]
    hidden_activation: 'Sine'
    last_activation: False
    xavier_init: True
    batch_norm: False 

  encoder:
    layers: [16, 256, 1]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False
 
  mapper: 
    layers: [1, 256, 16]
    hidden_activation: 'Sine'
    last_activation: 'Sine'
    xavier_init: True
    batch_norm: False
  
decoder_parameters:
  use_scvi_decoder:
    apply: True
    n_layers: 3
    n_hidden: 256
    #pxr_lr: 0.0001 #0.001

embedders:
  time_embedder:
    n_classes: 11
    n_dim: 6

optimizers: 
  condition_optimizers:
    models: ['time_embedder']
    lr: [0.001]

  decoder_optimizer:
    models: ['encoder_pretrain', 'decoder']
    lr: [0.0001, 0.0001, 0.0001] # Third for PXR !

losses:

  rec_from_latent_pretrain:
    fnc_name: 'nb_loss'
    apply: True
    pred_key: 'px_l'
    gt_key: 'x_inp'
    activate_at: 0
    stop_at: +.inf
    weight:  0.00001
    gradient_flow: 'all'

  recover_latent:
    fnc_name: 'recover_latent'
    apply: True
    latent_key: 'pre_latent'
    post_latent_key: 'map_latent_summed'
    activate_at: 0
    stop_at: +.inf
    weight: 0.002
    gradient_flow: 'all'

 
train:
  set_seed: 1
  
  main_train:
    epochs: 521 #1001

  evaluate: True

  criterions:

    r2_mean_criterion/10_all:
      criterion: 'max'

evaluations:
  context_transfer_criterion:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['all']
    kwargs:
      rec_key: 'reconstructed_collapse'
      gt_key: 'x_inp' #
      adata_degs_key: 'rank_genes_groups_time' #
      variables_of_interest: ['time', 'predType']
      stim_name: 'Insert_OOD' # Should by dynamic
      eval_by: 'predType'
      ood_covariate: 'Epi_Luminal_2Psca' # Should be dynamic
      subset_covars: ['Epi_Luminal_1', 'Epi_Luminal_2Psca']
      normalize_log: True
      n_degs_list: [10, 20, 50, 100]

      metrics: ['r2_mean', 'r2_delta', 'wasserstein', 'r2_var']
      wasserstein_degs_list: [10, 100]
      
      subsample:
        gt:
          time: 'Insert_OOD'

        pred:
          time: 'T00'

        ctrl:
          time: 'T00'

        collapse:
          time_mapper:
            apply: False
            collapse_name: null
          
  evaluate_reconstruction:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['train'] #['train', 'val']
    kwargs:
      rec_key: 'reconstructed'
      gt_key: 'x_inp'

  get_mig:
    interval: 40
    start_eval: 0
    stop_eval: +.inf
    dataloaders: ['train'] #['train', 'val']
    kwargs:
      latent_key: 'dis_latent_stack'
      label_keys: ['time']

save_experiment:
  apply: False
  experiment_path: 'weights/' #'experiments/oods1_2048bs_meanfix'
  save_weights:
    apply: False
    interval: 200
    
  save_best_weights:
    apply: False

save_gradients: 
  apply: True
  interval: 100